export enum Resource {
  AUTH = "auth/",
  SIGNUP = "auth/signup/",
  RESEND_EMAIL = "auth/resend-email/",
  EMAIL_CONFIRMATION = "auth/email-confirmation/",
  LOGIN = "auth/signin/",
  USER = 'user/',
  USER_FRIENDS = 'user/friends/',
  USER_REQUEST = 'user/request/',
  USER_FOLLOW = 'user/follow/',
  USER_FOLLOW_REQUESTS_AND_FOLLOWS = 'user/followRequestsAndFollows/',
  FILE = 'file/',
  WORKOUT = 'workout/',
  UNPOSTED = 'workout/unposted/',
  NOTIFICATION = "notification/",
  POST = "post/",
  FEEDBACK = "feedback/",
}
